# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainPages = QtWidgets.QStackedWidget(self.centralwidget)
        self.MainPages.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.MainPages.setMinimumSize(QtCore.QSize(800, 600))
        self.MainPages.setMaximumSize(QtCore.QSize(800, 600))
        self.MainPages.setObjectName("MainPages")
        self.pg_authorisation = QtWidgets.QWidget()
        self.pg_authorisation.setObjectName("pg_authorisation")
        self.pb_auth_Login = QtWidgets.QPushButton(self.pg_authorisation)
        self.pb_auth_Login.setGeometry(QtCore.QRect(290, 280, 141, 41))
        self.pb_auth_Login.setObjectName("pb_auth_Login")
        self.label = QtWidgets.QLabel(self.pg_authorisation)
        self.label.setGeometry(QtCore.QRect(160, 140, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pb_auth_registration = QtWidgets.QPushButton(self.pg_authorisation)
        self.pb_auth_registration.setGeometry(QtCore.QRect(300, 550, 171, 41))
        self.pb_auth_registration.setObjectName("pb_auth_registration")
        self.label_2 = QtWidgets.QLabel(self.pg_authorisation)
        self.label_2.setGeometry(QtCore.QRect(270, 510, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pb_auth_choseFileWithKey = QtWidgets.QPushButton(self.pg_authorisation)
        self.pb_auth_choseFileWithKey.setGeometry(QtCore.QRect(310, 240, 91, 31))
        self.pb_auth_choseFileWithKey.setObjectName("pb_auth_choseFileWithKey")
        self.lbl_auth_pathToSecretKey = QtWidgets.QLabel(self.pg_authorisation)
        self.lbl_auth_pathToSecretKey.setGeometry(QtCore.QRect(160, 210, 321, 17))
        self.lbl_auth_pathToSecretKey.setObjectName("lbl_auth_pathToSecretKey")
        self.pb_main_Exit_2 = QtWidgets.QPushButton(self.pg_authorisation)
        self.pb_main_Exit_2.setGeometry(QtCore.QRect(690, 550, 101, 41))
        self.pb_main_Exit_2.setObjectName("pb_main_Exit_2")
        self.MainPages.addWidget(self.pg_authorisation)
        self.pg_registration = QtWidgets.QWidget()
        self.pg_registration.setObjectName("pg_registration")
        self.formLayoutWidget = QtWidgets.QWidget(self.pg_registration)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 170, 691, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.le_imya = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_imya.setObjectName("le_imya")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_imya)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.le_organization = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_organization.setObjectName("le_organization")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_organization)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.le_dateOfBirth = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_dateOfBirth.setObjectName("le_dateOfBirth")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_dateOfBirth)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.cb_registr_choseFileWithPrivateKey = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_registr_choseFileWithPrivateKey.setObjectName("cb_registr_choseFileWithPrivateKey")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cb_registr_choseFileWithPrivateKey)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.pb_generatePrivKey = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pb_generatePrivKey.setObjectName("pb_generatePrivKey")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pb_generatePrivKey)
        self.label_22 = QtWidgets.QLabel(self.pg_registration)
        self.label_22.setGeometry(QtCore.QRect(50, 10, 291, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.pg_registration)
        self.label_23.setGeometry(QtCore.QRect(50, 30, 611, 131))
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.pb_sendRegistReqv = QtWidgets.QPushButton(self.pg_registration)
        self.pb_sendRegistReqv.setGeometry(QtCore.QRect(470, 440, 261, 41))
        self.pb_sendRegistReqv.setObjectName("pb_sendRegistReqv")
        self.pb_registration_GoToAuth = QtWidgets.QPushButton(self.pg_registration)
        self.pb_registration_GoToAuth.setGeometry(QtCore.QRect(10, 550, 141, 41))
        self.pb_registration_GoToAuth.setObjectName("pb_registration_GoToAuth")
        self.pb_main_Exit_3 = QtWidgets.QPushButton(self.pg_registration)
        self.pb_main_Exit_3.setGeometry(QtCore.QRect(690, 550, 101, 41))
        self.pb_main_Exit_3.setObjectName("pb_main_Exit_3")
        self.MainPages.addWidget(self.pg_registration)
        self.pg_main = QtWidgets.QWidget()
        self.pg_main.setObjectName("pg_main")
        self.SW_menu = QtWidgets.QStackedWidget(self.pg_main)
        self.SW_menu.setGeometry(QtCore.QRect(200, 0, 600, 600))
        self.SW_menu.setObjectName("SW_menu")
        self.pg_accountInfo = QtWidgets.QWidget()
        self.pg_accountInfo.setObjectName("pg_accountInfo")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.pg_accountInfo)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 581, 91))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.lbl_imya = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_imya.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_imya.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_imya.setObjectName("lbl_imya")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_imya)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.lbl_organization = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_organization.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_organization.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_organization.setObjectName("lbl_organization")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_organization)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_31.setObjectName("label_31")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.lbl_dateOfBirth = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_dateOfBirth.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_dateOfBirth.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dateOfBirth.setObjectName("lbl_dateOfBirth")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_dateOfBirth)
        self.label_41 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_41.setObjectName("label_41")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.lbl_adress = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_adress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_adress.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_adress.setObjectName("lbl_adress")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_adress)
        self.label_32 = QtWidgets.QLabel(self.pg_accountInfo)
        self.label_32.setGeometry(QtCore.QRect(10, 24, 341, 20))
        self.label_32.setObjectName("label_32")
        self.pb_makeRequestToBeExpert = QtWidgets.QPushButton(self.pg_accountInfo)
        self.pb_makeRequestToBeExpert.setGeometry(QtCore.QRect(170, 560, 241, 31))
        self.pb_makeRequestToBeExpert.setObjectName("pb_makeRequestToBeExpert")
        self.label_43 = QtWidgets.QLabel(self.pg_accountInfo)
        self.label_43.setGeometry(QtCore.QRect(20, 470, 531, 71))
        self.label_43.setWordWrap(True)
        self.label_43.setObjectName("label_43")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.pg_accountInfo)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(110, 430, 331, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_44 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout.addWidget(self.label_44)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lbl_isExpert = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lbl_isExpert.setObjectName("lbl_isExpert")
        self.horizontalLayout.addWidget(self.lbl_isExpert)
        self.SW_menu.addWidget(self.pg_accountInfo)
        self.pg_eventinfo = QtWidgets.QWidget()
        self.pg_eventinfo.setObjectName("pg_eventinfo")
        self.formWidget_3 = QtWidgets.QWidget(self.pg_eventinfo)
        self.formWidget_3.setGeometry(QtCore.QRect(10, 70, 571, 251))
        self.formWidget_3.setObjectName("formWidget_3")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formWidget_3)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_46 = QtWidgets.QLabel(self.formWidget_3)
        self.label_46.setObjectName("label_46")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.lbl_eventInfo_idevent = QtWidgets.QLabel(self.formWidget_3)
        self.lbl_eventInfo_idevent.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_eventInfo_idevent.setObjectName("lbl_eventInfo_idevent")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_eventInfo_idevent)
        self.label_49 = QtWidgets.QLabel(self.formWidget_3)
        self.label_49.setObjectName("label_49")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.lbl_eventInfo_eventCreator = QtWidgets.QLabel(self.formWidget_3)
        self.lbl_eventInfo_eventCreator.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_eventInfo_eventCreator.setObjectName("lbl_eventInfo_eventCreator")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_eventInfo_eventCreator)
        self.label_51 = QtWidgets.QLabel(self.formWidget_3)
        self.label_51.setObjectName("label_51")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.lbl_eventInfo_eventName = QtWidgets.QLabel(self.formWidget_3)
        self.lbl_eventInfo_eventName.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_eventInfo_eventName.setObjectName("lbl_eventInfo_eventName")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_eventInfo_eventName)
        self.label_55 = QtWidgets.QLabel(self.formWidget_3)
        self.label_55.setObjectName("label_55")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_55)
        self.lbl_eventInfo_eventDate = QtWidgets.QLabel(self.formWidget_3)
        self.lbl_eventInfo_eventDate.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_eventInfo_eventDate.setObjectName("lbl_eventInfo_eventDate")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_eventInfo_eventDate)
        self.label_50 = QtWidgets.QLabel(self.formWidget_3)
        self.label_50.setObjectName("label_50")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_50)
        self.lbl_eventInfo_EventCompetence = QtWidgets.QLabel(self.formWidget_3)
        self.lbl_eventInfo_EventCompetence.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_eventInfo_EventCompetence.setObjectName("lbl_eventInfo_EventCompetence")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lbl_eventInfo_EventCompetence)
        self.label_57 = QtWidgets.QLabel(self.formWidget_3)
        self.label_57.setObjectName("label_57")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_57)
        self.lbl_eventInfo_eventRating = QtWidgets.QLabel(self.formWidget_3)
        self.lbl_eventInfo_eventRating.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_eventInfo_eventRating.setObjectName("lbl_eventInfo_eventRating")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lbl_eventInfo_eventRating)
        self.label_61 = QtWidgets.QLabel(self.formWidget_3)
        self.label_61.setObjectName("label_61")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_61)
        self.lbl_eventInfo_expertCount = QtWidgets.QLabel(self.formWidget_3)
        self.lbl_eventInfo_expertCount.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_eventInfo_expertCount.setObjectName("lbl_eventInfo_expertCount")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lbl_eventInfo_expertCount)
        self.label_56 = QtWidgets.QLabel(self.formWidget_3)
        self.label_56.setObjectName("label_56")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_56)
        self.pb_EventInfo_getExpertList = QtWidgets.QPushButton(self.formWidget_3)
        self.pb_EventInfo_getExpertList.setObjectName("pb_EventInfo_getExpertList")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.pb_EventInfo_getExpertList)
        self.label_63 = QtWidgets.QLabel(self.formWidget_3)
        self.label_63.setObjectName("label_63")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_63)
        self.pb_EventInfo_getUserList = QtWidgets.QPushButton(self.formWidget_3)
        self.pb_EventInfo_getUserList.setObjectName("pb_EventInfo_getUserList")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.pb_EventInfo_getUserList)
        self.label_64 = QtWidgets.QLabel(self.formWidget_3)
        self.label_64.setObjectName("label_64")
        self.formLayout_6.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_64)
        self.lbl_eventInfo_Version = QtWidgets.QLabel(self.formWidget_3)
        self.lbl_eventInfo_Version.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_eventInfo_Version.setObjectName("lbl_eventInfo_Version")
        self.formLayout_6.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lbl_eventInfo_Version)
        self.cb_eventInfo_ChoseEvent = QtWidgets.QComboBox(self.pg_eventinfo)
        self.cb_eventInfo_ChoseEvent.setGeometry(QtCore.QRect(10, 40, 351, 21))
        self.cb_eventInfo_ChoseEvent.setObjectName("cb_eventInfo_ChoseEvent")
        self.label_62 = QtWidgets.QLabel(self.pg_eventinfo)
        self.label_62.setGeometry(QtCore.QRect(10, 20, 351, 16))
        self.label_62.setObjectName("label_62")
        self.label_58 = QtWidgets.QLabel(self.pg_eventinfo)
        self.label_58.setGeometry(QtCore.QRect(300, 330, 78, 17))
        self.label_58.setObjectName("label_58")
        self.tb_event_info = QtWidgets.QTextBrowser(self.pg_eventinfo)
        self.tb_event_info.setGeometry(QtCore.QRect(300, 350, 281, 221))
        self.tb_event_info.setObjectName("tb_event_info")
        self.tw_eventinfo_userlist = QtWidgets.QTableWidget(self.pg_eventinfo)
        self.tw_eventinfo_userlist.setGeometry(QtCore.QRect(0, 340, 281, 231))
        self.tw_eventinfo_userlist.setRowCount(1)
        self.tw_eventinfo_userlist.setColumnCount(3)
        self.tw_eventinfo_userlist.setObjectName("tw_eventinfo_userlist")
        self.tw_eventinfo_userlist.horizontalHeader().setVisible(False)
        self.tw_eventinfo_userlist.verticalHeader().setVisible(False)
        self.SW_menu.addWidget(self.pg_eventinfo)
        self.pg_createEvent = QtWidgets.QWidget()
        self.pg_createEvent.setObjectName("pg_createEvent")
        self.label_59 = QtWidgets.QLabel(self.pg_createEvent)
        self.label_59.setGeometry(QtCore.QRect(300, 330, 78, 17))
        self.label_59.setObjectName("label_59")
        self.tb_createEvent_info = QtWidgets.QTextBrowser(self.pg_createEvent)
        self.tb_createEvent_info.setGeometry(QtCore.QRect(300, 350, 281, 201))
        self.tb_createEvent_info.setMouseTracking(True)
        self.tb_createEvent_info.setObjectName("tb_createEvent_info")
        self.formWidget_4 = QtWidgets.QWidget(self.pg_createEvent)
        self.formWidget_4.setGeometry(QtCore.QRect(10, 70, 571, 251))
        self.formWidget_4.setObjectName("formWidget_4")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formWidget_4)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_53 = QtWidgets.QLabel(self.formWidget_4)
        self.label_53.setObjectName("label_53")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_53)
        self.le_createEvent_name = QtWidgets.QLineEdit(self.formWidget_4)
        self.le_createEvent_name.setObjectName("le_createEvent_name")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_createEvent_name)
        self.label_60 = QtWidgets.QLabel(self.formWidget_4)
        self.label_60.setObjectName("label_60")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_60)
        self.le_createEvent_date = QtWidgets.QLineEdit(self.formWidget_4)
        self.le_createEvent_date.setObjectName("le_createEvent_date")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_createEvent_date)
        self.label_54 = QtWidgets.QLabel(self.formWidget_4)
        self.label_54.setObjectName("label_54")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_54)
        self.le_createEvent_competence = QtWidgets.QLineEdit(self.formWidget_4)
        self.le_createEvent_competence.setObjectName("le_createEvent_competence")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_createEvent_competence)
        self.label_84 = QtWidgets.QLabel(self.formWidget_4)
        self.label_84.setObjectName("label_84")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_84)
        self.le_createEvent_rating = QtWidgets.QLineEdit(self.formWidget_4)
        self.le_createEvent_rating.setObjectName("le_createEvent_rating")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_createEvent_rating)
        self.label_86 = QtWidgets.QLabel(self.formWidget_4)
        self.label_86.setObjectName("label_86")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_86)
        self.pb_createEvent_getExpertList = QtWidgets.QPushButton(self.formWidget_4)
        self.pb_createEvent_getExpertList.setObjectName("pb_createEvent_getExpertList")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pb_createEvent_getExpertList)
        self.label_87 = QtWidgets.QLabel(self.formWidget_4)
        self.label_87.setObjectName("label_87")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_87)
        self.pb_createEvent_getUserList = QtWidgets.QPushButton(self.formWidget_4)
        self.pb_createEvent_getUserList.setObjectName("pb_createEvent_getUserList")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pb_createEvent_getUserList)
        self.label_88 = QtWidgets.QLabel(self.formWidget_4)
        self.label_88.setObjectName("label_88")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_88)
        self.le_createEvent_Version = QtWidgets.QLineEdit(self.formWidget_4)
        self.le_createEvent_Version.setObjectName("le_createEvent_Version")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.le_createEvent_Version)
        self.pb_createEvent_deleteUser = QtWidgets.QPushButton(self.pg_createEvent)
        self.pb_createEvent_deleteUser.setGeometry(QtCore.QRect(130, 540, 111, 27))
        self.pb_createEvent_deleteUser.setObjectName("pb_createEvent_deleteUser")
        self.pb_createEvent_addUer = QtWidgets.QPushButton(self.pg_createEvent)
        self.pb_createEvent_addUer.setGeometry(QtCore.QRect(10, 540, 111, 27))
        self.pb_createEvent_addUer.setObjectName("pb_createEvent_addUer")
        self.pb_createEvent_PushCreateEventRequest = QtWidgets.QPushButton(self.pg_createEvent)
        self.pb_createEvent_PushCreateEventRequest.setGeometry(QtCore.QRect(420, 566, 161, 31))
        self.pb_createEvent_PushCreateEventRequest.setObjectName("pb_createEvent_PushCreateEventRequest")
        self.tw_createEvent_UserList = QtWidgets.QTableWidget(self.pg_createEvent)
        self.tw_createEvent_UserList.setGeometry(QtCore.QRect(10, 320, 281, 101))
        self.tw_createEvent_UserList.setRowCount(1)
        self.tw_createEvent_UserList.setColumnCount(3)
        self.tw_createEvent_UserList.setObjectName("tw_createEvent_UserList")
        self.tw_createEvent_UserList.horizontalHeader().setVisible(False)
        self.tw_createEvent_UserList.verticalHeader().setVisible(False)
        self.tw_createEvent_addedUserList = QtWidgets.QTableWidget(self.pg_createEvent)
        self.tw_createEvent_addedUserList.setGeometry(QtCore.QRect(10, 430, 281, 101))
        self.tw_createEvent_addedUserList.setRowCount(1)
        self.tw_createEvent_addedUserList.setColumnCount(3)
        self.tw_createEvent_addedUserList.setObjectName("tw_createEvent_addedUserList")
        self.tw_createEvent_addedUserList.horizontalHeader().setVisible(False)
        self.tw_createEvent_addedUserList.verticalHeader().setVisible(False)
        self.SW_menu.addWidget(self.pg_createEvent)
        self.pg_changeEvent = QtWidgets.QWidget()
        self.pg_changeEvent.setObjectName("pg_changeEvent")
        self.label_83 = QtWidgets.QLabel(self.pg_changeEvent)
        self.label_83.setGeometry(QtCore.QRect(10, 20, 351, 16))
        self.label_83.setObjectName("label_83")
        self.formWidget_7 = QtWidgets.QWidget(self.pg_changeEvent)
        self.formWidget_7.setGeometry(QtCore.QRect(10, 70, 571, 251))
        self.formWidget_7.setObjectName("formWidget_7")
        self.formLayout_14 = QtWidgets.QFormLayout(self.formWidget_7)
        self.formLayout_14.setContentsMargins(0, 0, 0, 0)
        self.formLayout_14.setObjectName("formLayout_14")
        self.label_144 = QtWidgets.QLabel(self.formWidget_7)
        self.label_144.setObjectName("label_144")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_144)
        self.le_changeEvent_name = QtWidgets.QLineEdit(self.formWidget_7)
        self.le_changeEvent_name.setObjectName("le_changeEvent_name")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_changeEvent_name)
        self.label_145 = QtWidgets.QLabel(self.formWidget_7)
        self.label_145.setObjectName("label_145")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_145)
        self.le_changeEvent_date = QtWidgets.QLineEdit(self.formWidget_7)
        self.le_changeEvent_date.setObjectName("le_changeEvent_date")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_changeEvent_date)
        self.label_146 = QtWidgets.QLabel(self.formWidget_7)
        self.label_146.setObjectName("label_146")
        self.formLayout_14.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_146)
        self.le_changeEvent_competence = QtWidgets.QLineEdit(self.formWidget_7)
        self.le_changeEvent_competence.setObjectName("le_changeEvent_competence")
        self.formLayout_14.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_changeEvent_competence)
        self.label_147 = QtWidgets.QLabel(self.formWidget_7)
        self.label_147.setObjectName("label_147")
        self.formLayout_14.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_147)
        self.le_changeEvent_rating = QtWidgets.QLineEdit(self.formWidget_7)
        self.le_changeEvent_rating.setObjectName("le_changeEvent_rating")
        self.formLayout_14.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_changeEvent_rating)
        self.label_149 = QtWidgets.QLabel(self.formWidget_7)
        self.label_149.setObjectName("label_149")
        self.formLayout_14.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_149)
        self.pb_changeEvent_getExpertList = QtWidgets.QPushButton(self.formWidget_7)
        self.pb_changeEvent_getExpertList.setObjectName("pb_changeEvent_getExpertList")
        self.formLayout_14.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pb_changeEvent_getExpertList)
        self.label_150 = QtWidgets.QLabel(self.formWidget_7)
        self.label_150.setObjectName("label_150")
        self.formLayout_14.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_150)
        self.pb_changeEvent_getUserList = QtWidgets.QPushButton(self.formWidget_7)
        self.pb_changeEvent_getUserList.setObjectName("pb_changeEvent_getUserList")
        self.formLayout_14.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pb_changeEvent_getUserList)
        self.label_152 = QtWidgets.QLabel(self.pg_changeEvent)
        self.label_152.setGeometry(QtCore.QRect(300, 330, 78, 17))
        self.label_152.setObjectName("label_152")
        self.pb_changeEvent_deleteUser = QtWidgets.QPushButton(self.pg_changeEvent)
        self.pb_changeEvent_deleteUser.setGeometry(QtCore.QRect(130, 540, 111, 27))
        self.pb_changeEvent_deleteUser.setObjectName("pb_changeEvent_deleteUser")
        self.pb_changeEvent_addUer = QtWidgets.QPushButton(self.pg_changeEvent)
        self.pb_changeEvent_addUer.setGeometry(QtCore.QRect(10, 540, 111, 27))
        self.pb_changeEvent_addUer.setObjectName("pb_changeEvent_addUer")
        self.pb_changeEvent_PushCreateEventRequest = QtWidgets.QPushButton(self.pg_changeEvent)
        self.pb_changeEvent_PushCreateEventRequest.setGeometry(QtCore.QRect(420, 566, 161, 31))
        self.pb_changeEvent_PushCreateEventRequest.setObjectName("pb_changeEvent_PushCreateEventRequest")
        self.cb_changeEvent_ChoseEvent = QtWidgets.QComboBox(self.pg_changeEvent)
        self.cb_changeEvent_ChoseEvent.setGeometry(QtCore.QRect(10, 40, 351, 21))
        self.cb_changeEvent_ChoseEvent.setObjectName("cb_changeEvent_ChoseEvent")
        self.tw_changeEvent_UserList = QtWidgets.QTableWidget(self.pg_changeEvent)
        self.tw_changeEvent_UserList.setGeometry(QtCore.QRect(10, 330, 281, 91))
        self.tw_changeEvent_UserList.setRowCount(1)
        self.tw_changeEvent_UserList.setColumnCount(3)
        self.tw_changeEvent_UserList.setObjectName("tw_changeEvent_UserList")
        self.tw_changeEvent_UserList.horizontalHeader().setVisible(False)
        self.tw_changeEvent_UserList.verticalHeader().setVisible(False)
        self.tw_changeEvent_addedUserList = QtWidgets.QTableWidget(self.pg_changeEvent)
        self.tw_changeEvent_addedUserList.setGeometry(QtCore.QRect(10, 430, 281, 101))
        self.tw_changeEvent_addedUserList.setRowCount(1)
        self.tw_changeEvent_addedUserList.setColumnCount(3)
        self.tw_changeEvent_addedUserList.setObjectName("tw_changeEvent_addedUserList")
        self.tw_changeEvent_addedUserList.horizontalHeader().setVisible(False)
        self.tw_changeEvent_addedUserList.verticalHeader().setVisible(False)
        self.te_changeEvent_Info = QtWidgets.QTextEdit(self.pg_changeEvent)
        self.te_changeEvent_Info.setGeometry(QtCore.QRect(300, 350, 281, 211))
        self.te_changeEvent_Info.setObjectName("te_changeEvent_Info")
        self.SW_menu.addWidget(self.pg_changeEvent)
        self.pg_request = QtWidgets.QWidget()
        self.pg_request.setObjectName("pg_request")
        self.pb_request_confirmRequest = QtWidgets.QPushButton(self.pg_request)
        self.pb_request_confirmRequest.setGeometry(QtCore.QRect(70, 560, 101, 27))
        self.pb_request_confirmRequest.setObjectName("pb_request_confirmRequest")
        self.Widget_Request_infto = QtWidgets.QWidget(self.pg_request)
        self.Widget_Request_infto.setEnabled(True)
        self.Widget_Request_infto.setGeometry(QtCore.QRect(280, 10, 301, 551))
        self.Widget_Request_infto.setObjectName("Widget_Request_infto")
        self.tb_request_after = QtWidgets.QTextBrowser(self.Widget_Request_infto)
        self.tb_request_after.setEnabled(True)
        self.tb_request_after.setGeometry(QtCore.QRect(10, 270, 271, 271))
        self.tb_request_after.setObjectName("tb_request_after")
        self.tb_request_before = QtWidgets.QTextBrowser(self.Widget_Request_infto)
        self.tb_request_before.setEnabled(True)
        self.tb_request_before.setGeometry(QtCore.QRect(10, 20, 271, 221))
        self.tb_request_before.setObjectName("tb_request_before")
        self.label_10 = QtWidgets.QLabel(self.Widget_Request_infto)
        self.label_10.setGeometry(QtCore.QRect(10, 250, 67, 17))
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.Widget_Request_infto)
        self.label_9.setEnabled(True)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 67, 17))
        self.label_9.setObjectName("label_9")
        self.cb_request_mode = QtWidgets.QComboBox(self.pg_request)
        self.cb_request_mode.setGeometry(QtCore.QRect(10, 10, 171, 31))
        self.cb_request_mode.setObjectName("cb_request_mode")
        self.tw_requestList = QtWidgets.QTableWidget(self.pg_request)
        self.tw_requestList.setGeometry(QtCore.QRect(10, 50, 256, 491))
        self.tw_requestList.setColumnCount(3)
        self.tw_requestList.setObjectName("tw_requestList")
        self.tw_requestList.setRowCount(0)
        self.tw_requestList.horizontalHeader().setVisible(False)
        self.tw_requestList.horizontalHeader().setHighlightSections(True)
        self.tw_requestList.horizontalHeader().setMinimumSectionSize(80)
        self.tw_requestList.verticalHeader().setVisible(False)
        self.SW_menu.addWidget(self.pg_request)
        self.pg_lowerRequest = QtWidgets.QWidget()
        self.pg_lowerRequest.setObjectName("pg_lowerRequest")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.pg_lowerRequest)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(300, 60, 291, 231))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lbl_lowerRequest_Address = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.lbl_lowerRequest_Address.setObjectName("lbl_lowerRequest_Address")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_lowerRequest_Address)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lbl_lowerRequest_Name = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.lbl_lowerRequest_Name.setObjectName("lbl_lowerRequest_Name")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_lowerRequest_Name)
        self.lbl_lowerRequest_Birthday = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.lbl_lowerRequest_Birthday.setObjectName("lbl_lowerRequest_Birthday")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_lowerRequest_Birthday)
        self.lbl_lowerRequest_organization = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.lbl_lowerRequest_organization.setObjectName("lbl_lowerRequest_organization")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_lowerRequest_organization)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_157 = QtWidgets.QLabel(self.pg_lowerRequest)
        self.label_157.setGeometry(QtCore.QRect(300, 40, 111, 17))
        self.label_157.setObjectName("label_157")
        self.pb_lowerRequest_PushRequest = QtWidgets.QPushButton(self.pg_lowerRequest)
        self.pb_lowerRequest_PushRequest.setGeometry(QtCore.QRect(300, 300, 111, 27))
        self.pb_lowerRequest_PushRequest.setObjectName("pb_lowerRequest_PushRequest")
        self.tw_lowerRequest_UserList = QtWidgets.QTableWidget(self.pg_lowerRequest)
        self.tw_lowerRequest_UserList.setGeometry(QtCore.QRect(10, 60, 271, 371))
        self.tw_lowerRequest_UserList.setRowCount(1)
        self.tw_lowerRequest_UserList.setColumnCount(3)
        self.tw_lowerRequest_UserList.setObjectName("tw_lowerRequest_UserList")
        self.tw_lowerRequest_UserList.verticalHeader().setVisible(False)
        self.SW_menu.addWidget(self.pg_lowerRequest)
        self.verticalWidget = QtWidgets.QWidget(self.pg_main)
        self.verticalWidget.setGeometry(QtCore.QRect(0, 0, 200, 600))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_24 = QtWidgets.QLabel(self.verticalWidget)
        self.label_24.setEnabled(True)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_24.setObjectName("label_24")
        self.verticalLayout_2.addWidget(self.label_24)
        self.pb_menu_aboutAccount = QtWidgets.QPushButton(self.verticalWidget)
        self.pb_menu_aboutAccount.setObjectName("pb_menu_aboutAccount")
        self.verticalLayout_2.addWidget(self.pb_menu_aboutAccount)
        self.pb_menu_eventInfo = QtWidgets.QPushButton(self.verticalWidget)
        self.pb_menu_eventInfo.setObjectName("pb_menu_eventInfo")
        self.verticalLayout_2.addWidget(self.pb_menu_eventInfo)
        self.wdgt_expertMenu = QtWidgets.QWidget(self.verticalWidget)
        self.wdgt_expertMenu.setEnabled(True)
        self.wdgt_expertMenu.setObjectName("wdgt_expertMenu")
        self.blyt_expertPanel = QtWidgets.QVBoxLayout(self.wdgt_expertMenu)
        self.blyt_expertPanel.setObjectName("blyt_expertPanel")
        self.pb_menu_createEvent = QtWidgets.QPushButton(self.wdgt_expertMenu)
        self.pb_menu_createEvent.setObjectName("pb_menu_createEvent")
        self.blyt_expertPanel.addWidget(self.pb_menu_createEvent)
        self.pb_menu_changeEvent = QtWidgets.QPushButton(self.wdgt_expertMenu)
        self.pb_menu_changeEvent.setObjectName("pb_menu_changeEvent")
        self.blyt_expertPanel.addWidget(self.pb_menu_changeEvent)
        self.pb_menu_unconfirmedRequest = QtWidgets.QPushButton(self.wdgt_expertMenu)
        self.pb_menu_unconfirmedRequest.setObjectName("pb_menu_unconfirmedRequest")
        self.blyt_expertPanel.addWidget(self.pb_menu_unconfirmedRequest)
        self.pb_menu_lower = QtWidgets.QPushButton(self.wdgt_expertMenu)
        self.pb_menu_lower.setObjectName("pb_menu_lower")
        self.blyt_expertPanel.addWidget(self.pb_menu_lower)
        self.verticalLayout_2.addWidget(self.wdgt_expertMenu)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pb_menu_StartMine = QtWidgets.QPushButton(self.verticalWidget)
        self.pb_menu_StartMine.setCheckable(True)
        self.pb_menu_StartMine.setObjectName("pb_menu_StartMine")
        self.verticalLayout_2.addWidget(self.pb_menu_StartMine)
        self.pb_mainLogOut = QtWidgets.QPushButton(self.verticalWidget)
        self.pb_mainLogOut.setObjectName("pb_mainLogOut")
        self.verticalLayout_2.addWidget(self.pb_mainLogOut)
        self.pb_main_Exit = QtWidgets.QPushButton(self.verticalWidget)
        self.pb_main_Exit.setObjectName("pb_main_Exit")
        self.verticalLayout_2.addWidget(self.pb_main_Exit)
        self.MainPages.addWidget(self.pg_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.MainPages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ver 1.0"))
        self.pb_auth_Login.setText(_translate("MainWindow", "Войти"))
        self.label.setText(_translate("MainWindow", "выберите выданный вам при регистрации закрытый ключ"))
        self.pb_auth_registration.setText(_translate("MainWindow", "Зарегестрировать"))
        self.label_2.setText(_translate("MainWindow", "Еще нет аккаунта?"))
        self.pb_auth_choseFileWithKey.setText(_translate("MainWindow", "Выбрать"))
        self.lbl_auth_pathToSecretKey.setText(_translate("MainWindow", "/home/arthur/Git_folder/PrivateKey_0"))
        self.pb_main_Exit_2.setText(_translate("MainWindow", "Выйти"))
        self.label_4.setText(_translate("MainWindow", "Имя:"))
        self.label_7.setText(_translate("MainWindow", "Организация:"))
        self.label_14.setText(_translate("MainWindow", "Дата рождения:"))
        self.label_21.setText(_translate("MainWindow", "Закрытый ключ:"))
        self.label_3.setText(_translate("MainWindow", "Сгенерировать закрытый ключ"))
        self.pb_generatePrivKey.setText(_translate("MainWindow", "Сгенерировать"))
        self.label_22.setText(_translate("MainWindow", "Добро пожаловать в окно регистрации"))
        self.label_23.setText(_translate("MainWindow", "Внимание! После регистрации и принятии транзакции сетью изменить поля будет нельзя, отнеситесь к заполнению этих полей ответственно. Нажмите на кнопку \"Генерация\", чтобы создать закрытый ключ. Самому закрытый ключ создать нельзя в целях безопасности. Закрытый ключ необходимо запомнить или спрятать так, чтобы никто не мог иметь к нему доступа. Закрытый ключ в понимании обычного пользователя является одновременно и логином и паролем, восстановить который нельзя."))
        self.pb_sendRegistReqv.setText(_translate("MainWindow", "Отправить запрос на регистрацию"))
        self.pb_registration_GoToAuth.setText(_translate("MainWindow", "Авторизация"))
        self.pb_main_Exit_3.setText(_translate("MainWindow", "Выйти"))
        self.label_25.setText(_translate("MainWindow", "Имя:"))
        self.lbl_imya.setText(_translate("MainWindow", "noname"))
        self.label_28.setText(_translate("MainWindow", "Организация:"))
        self.lbl_organization.setText(_translate("MainWindow", "default"))
        self.label_31.setText(_translate("MainWindow", "Дата рождения:"))
        self.lbl_dateOfBirth.setText(_translate("MainWindow", "default"))
        self.label_41.setText(_translate("MainWindow", "Адрес:"))
        self.lbl_adress.setText(_translate("MainWindow", "default"))
        self.label_32.setText(_translate("MainWindow", "Информация, привязанная к вашему аккаунту"))
        self.pb_makeRequestToBeExpert.setText(_translate("MainWindow", "Подать заявку на роль эксперта"))
        self.label_43.setText(_translate("MainWindow", "Если ваш аккаунт в системе должен быть в роли эксперта, то вы должны подать заявку и ожидать подтверждения 3мя экспертами. В протином случае ни в коем случае не подавайте заявку на получение роли эксперта, иначе вы можете быть забанены "))
        self.label_44.setText(_translate("MainWindow", "Статус на данный момент:"))
        self.lbl_isExpert.setText(_translate("MainWindow", "default"))
        self.label_46.setText(_translate("MainWindow", "Id События"))
        self.lbl_eventInfo_idevent.setText(_translate("MainWindow", "..."))
        self.label_49.setText(_translate("MainWindow", "Создатель:"))
        self.lbl_eventInfo_eventCreator.setText(_translate("MainWindow", "..."))
        self.label_51.setText(_translate("MainWindow", "Название:"))
        self.lbl_eventInfo_eventName.setText(_translate("MainWindow", "..."))
        self.label_55.setText(_translate("MainWindow", "Дата:"))
        self.lbl_eventInfo_eventDate.setText(_translate("MainWindow", "..."))
        self.label_50.setText(_translate("MainWindow", "Компетенция:"))
        self.lbl_eventInfo_EventCompetence.setText(_translate("MainWindow", "..."))
        self.label_57.setText(_translate("MainWindow", "Рейтинг:"))
        self.lbl_eventInfo_eventRating.setText(_translate("MainWindow", "..."))
        self.label_61.setText(_translate("MainWindow", "Количество Экспертов:"))
        self.lbl_eventInfo_expertCount.setText(_translate("MainWindow", "..."))
        self.label_56.setText(_translate("MainWindow", "Эксперты:"))
        self.pb_EventInfo_getExpertList.setText(_translate("MainWindow", "Список экспертов"))
        self.label_63.setText(_translate("MainWindow", "Пользователи:"))
        self.pb_EventInfo_getUserList.setText(_translate("MainWindow", "Список пользователей"))
        self.label_64.setText(_translate("MainWindow", "Версия:"))
        self.lbl_eventInfo_Version.setText(_translate("MainWindow", "..."))
        self.label_62.setText(_translate("MainWindow", "Список доступных мероприятий"))
        self.label_58.setText(_translate("MainWindow", "Описание:"))
        self.label_59.setText(_translate("MainWindow", "Описание:"))
        self.label_53.setText(_translate("MainWindow", "Название:"))
        self.label_60.setText(_translate("MainWindow", "Дата:"))
        self.label_54.setText(_translate("MainWindow", "Компетенция:"))
        self.label_84.setText(_translate("MainWindow", "Рейтинг:"))
        self.label_86.setText(_translate("MainWindow", "Эксперты:"))
        self.pb_createEvent_getExpertList.setText(_translate("MainWindow", "Список экспертов"))
        self.label_87.setText(_translate("MainWindow", "Пользователи:"))
        self.pb_createEvent_getUserList.setText(_translate("MainWindow", "Список пользователей"))
        self.label_88.setText(_translate("MainWindow", "Версия:"))
        self.pb_createEvent_deleteUser.setText(_translate("MainWindow", "Удалить"))
        self.pb_createEvent_addUer.setText(_translate("MainWindow", "Добавить"))
        self.pb_createEvent_PushCreateEventRequest.setText(_translate("MainWindow", "Отправить"))
        self.label_83.setText(_translate("MainWindow", "Список доступных мероприятий"))
        self.label_144.setText(_translate("MainWindow", "Название:"))
        self.label_145.setText(_translate("MainWindow", "Дата:"))
        self.label_146.setText(_translate("MainWindow", "Компетенция:"))
        self.label_147.setText(_translate("MainWindow", "Рейтинг:"))
        self.label_149.setText(_translate("MainWindow", "Эксперты:"))
        self.pb_changeEvent_getExpertList.setText(_translate("MainWindow", "Список экспертов"))
        self.label_150.setText(_translate("MainWindow", "Пользователи:"))
        self.pb_changeEvent_getUserList.setText(_translate("MainWindow", "Список пользователей"))
        self.label_152.setText(_translate("MainWindow", "Описание:"))
        self.pb_changeEvent_deleteUser.setText(_translate("MainWindow", "Удалить"))
        self.pb_changeEvent_addUer.setText(_translate("MainWindow", "Добавить"))
        self.pb_changeEvent_PushCreateEventRequest.setText(_translate("MainWindow", "Отправить"))
        self.pb_request_confirmRequest.setText(_translate("MainWindow", "Подтвердить"))
        self.label_10.setText(_translate("MainWindow", "После:"))
        self.label_9.setText(_translate("MainWindow", "До:"))
        self.label_12.setText(_translate("MainWindow", "Address:"))
        self.lbl_lowerRequest_Address.setText(_translate("MainWindow", "..."))
        self.label_13.setText(_translate("MainWindow", "Name:"))
        self.lbl_lowerRequest_Name.setText(_translate("MainWindow", "..."))
        self.lbl_lowerRequest_Birthday.setText(_translate("MainWindow", "..."))
        self.lbl_lowerRequest_organization.setText(_translate("MainWindow", "..."))
        self.label_16.setText(_translate("MainWindow", "Birthday:"))
        self.label_15.setText(_translate("MainWindow", "Organization:"))
        self.label_157.setText(_translate("MainWindow", "Пользователь"))
        self.pb_lowerRequest_PushRequest.setText(_translate("MainWindow", "Разжаловать"))
        self.label_24.setText(_translate("MainWindow", "Меню"))
        self.pb_menu_aboutAccount.setText(_translate("MainWindow", "Об аккаунте"))
        self.pb_menu_eventInfo.setText(_translate("MainWindow", "Мероприятия"))
        self.pb_menu_createEvent.setText(_translate("MainWindow", "Создать мероприятие"))
        self.pb_menu_changeEvent.setText(_translate("MainWindow", "Изменит мероприятие"))
        self.pb_menu_unconfirmedRequest.setText(_translate("MainWindow", "Запросы"))
        self.pb_menu_lower.setText(_translate("MainWindow", "Заявка на разжалование"))
        self.pb_menu_StartMine.setText(_translate("MainWindow", "Майнить"))
        self.pb_mainLogOut.setText(_translate("MainWindow", "Logout"))
        self.pb_main_Exit.setText(_translate("MainWindow", "Выйти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

