# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainMenu'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainPages = QtWidgets.QStackedWidget(self.centralwidget)
        self.MainPages.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.MainPages.setMinimumSize(QtCore.QSize(800, 600))
        self.MainPages.setMaximumSize(QtCore.QSize(800, 600))
        self.MainPages.setObjectName("MainPages")
        self.pg_authorisation = QtWidgets.QWidget()
        self.pg_authorisation.setObjectName("pg_authorisation")
        self.pb_Enter = QtWidgets.QPushButton(self.pg_authorisation)
        self.pb_Enter.setGeometry(QtCore.QRect(160, 240, 141, 41))
        self.pb_Enter.setObjectName("pb_Enter")
        self.le_secretKey = QtWidgets.QLineEdit(self.pg_authorisation)
        self.le_secretKey.setGeometry(QtCore.QRect(160, 200, 311, 31))
        self.le_secretKey.setObjectName("le_secretKey")
        self.label = QtWidgets.QLabel(self.pg_authorisation)
        self.label.setGeometry(QtCore.QRect(160, 140, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pb_registration = QtWidgets.QPushButton(self.pg_authorisation)
        self.pb_registration.setGeometry(QtCore.QRect(300, 550, 171, 41))
        self.pb_registration.setObjectName("pb_registration")
        self.label_2 = QtWidgets.QLabel(self.pg_authorisation)
        self.label_2.setGeometry(QtCore.QRect(270, 510, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.MainPages.addWidget(self.pg_authorisation)
        self.pg_registration = QtWidgets.QWidget()
        self.pg_registration.setObjectName("pg_registration")
        self.label_3 = QtWidgets.QLabel(self.pg_registration)
        self.label_3.setGeometry(QtCore.QRect(50, 360, 211, 21))
        self.label_3.setObjectName("label_3")
        self.pb_generatePrivKey = QtWidgets.QPushButton(self.pg_registration)
        self.pb_generatePrivKey.setGeometry(QtCore.QRect(260, 360, 80, 22))
        self.pb_generatePrivKey.setObjectName("pb_generatePrivKey")
        self.formLayoutWidget = QtWidgets.QWidget(self.pg_registration)
        self.formLayoutWidget.setGeometry(QtCore.QRect(50, 160, 691, 227))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.le_imya = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_imya.setObjectName("le_imya")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_imya)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.le_familiya = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_familiya.setObjectName("le_familiya")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_familiya)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.le_otchestvo = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_otchestvo.setObjectName("le_otchestvo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_otchestvo)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.le_organization = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_organization.setObjectName("le_organization")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_organization)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.le_post = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_post.setObjectName("le_post")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.le_post)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.le_sekretKey = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_sekretKey.setReadOnly(True)
        self.le_sekretKey.setObjectName("le_sekretKey")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.le_sekretKey)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.le_dateOfBirth = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_dateOfBirth.setObjectName("le_dateOfBirth")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.le_dateOfBirth)
        self.label_22 = QtWidgets.QLabel(self.pg_registration)
        self.label_22.setGeometry(QtCore.QRect(50, 10, 251, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.pg_registration)
        self.label_23.setGeometry(QtCore.QRect(50, 30, 611, 91))
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.pb_sendRegistReqv = QtWidgets.QPushButton(self.pg_registration)
        self.pb_sendRegistReqv.setGeometry(QtCore.QRect(510, 380, 231, 41))
        self.pb_sendRegistReqv.setObjectName("pb_sendRegistReqv")
        self.MainPages.addWidget(self.pg_registration)
        self.pg_main = QtWidgets.QWidget()
        self.pg_main.setObjectName("pg_main")
        self.stackedWidget = QtWidgets.QStackedWidget(self.pg_main)
        self.stackedWidget.setGeometry(QtCore.QRect(200, 0, 600, 600))
        self.stackedWidget.setObjectName("stackedWidget")
        self.pg_accountInfo = QtWidgets.QWidget()
        self.pg_accountInfo.setObjectName("pg_accountInfo")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.pg_accountInfo)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 581, 203))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.lbl_imya = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_imya.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_imya.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_imya.setObjectName("lbl_imya")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_imya)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.lbl_familiya = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_familiya.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_familiya.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_familiya.setObjectName("lbl_familiya")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_familiya)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.lbl_otchestvo = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_otchestvo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_otchestvo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_otchestvo.setObjectName("lbl_otchestvo")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_otchestvo)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.lbl_organization = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_organization.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_organization.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_organization.setObjectName("lbl_organization")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_organization)
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_29.setObjectName("label_29")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.lbl_post = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_post.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_post.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_post.setObjectName("lbl_post")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lbl_post)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_31.setObjectName("label_31")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.lbl_dateOfBirth = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_dateOfBirth.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_dateOfBirth.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dateOfBirth.setObjectName("lbl_dateOfBirth")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lbl_dateOfBirth)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_30.setObjectName("label_30")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.lbl_secretKey = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_secretKey.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_secretKey.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_secretKey.setObjectName("lbl_secretKey")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lbl_secretKey)
        self.label_41 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_41.setObjectName("label_41")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.lbl_adress = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_adress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_adress.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_adress.setObjectName("lbl_adress")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lbl_adress)
        self.label_42 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_42.setObjectName("label_42")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.lbl_openKey = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_openKey.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_openKey.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_openKey.setObjectName("lbl_openKey")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lbl_openKey)
        self.label_32 = QtWidgets.QLabel(self.pg_accountInfo)
        self.label_32.setGeometry(QtCore.QRect(10, 24, 311, 20))
        self.label_32.setObjectName("label_32")
        self.pushButton_7 = QtWidgets.QPushButton(self.pg_accountInfo)
        self.pushButton_7.setGeometry(QtCore.QRect(170, 560, 241, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_43 = QtWidgets.QLabel(self.pg_accountInfo)
        self.label_43.setGeometry(QtCore.QRect(20, 470, 521, 81))
        self.label_43.setWordWrap(True)
        self.label_43.setObjectName("label_43")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.pg_accountInfo)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(110, 430, 331, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_44 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout.addWidget(self.label_44)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_45 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout.addWidget(self.label_45)
        self.stackedWidget.addWidget(self.pg_accountInfo)
        self.pg_eventList = QtWidgets.QWidget()
        self.pg_eventList.setObjectName("pg_eventList")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.pg_eventList)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 70, 351, 200))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_46 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_46.setObjectName("label_46")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.lbl_idEvent = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_idEvent.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_idEvent.setObjectName("lbl_idEvent")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_idEvent)
        self.label_49 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_49.setObjectName("label_49")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.label_51 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_51.setObjectName("label_51")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.label_55 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_55.setObjectName("label_55")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_55)
        self.lbl_EventCompetention = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_EventCompetention.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_EventCompetention.setObjectName("lbl_EventCompetention")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_EventCompetention)
        self.label_50 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_50.setObjectName("label_50")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_50)
        self.lbl_EventOcenka = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_EventOcenka.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_EventOcenka.setObjectName("lbl_EventOcenka")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lbl_EventOcenka)
        self.label_57 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_57.setObjectName("label_57")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_57)
        self.lbl_EventNumberOfExpert = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_EventNumberOfExpert.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_EventNumberOfExpert.setObjectName("lbl_EventNumberOfExpert")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lbl_EventNumberOfExpert)
        self.label_61 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_61.setObjectName("label_61")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_61)
        self.label_56 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_56.setObjectName("label_56")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_56)
        self.lbl_EventDate = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_EventDate.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_EventDate.setObjectName("lbl_EventDate")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_EventDate)
        self.lbl_EventCreator = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_EventCreator.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_EventCreator.setObjectName("lbl_EventCreator")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_EventCreator)
        self.btn_ShowExpertList = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.btn_ShowExpertList.setObjectName("btn_ShowExpertList")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.btn_ShowExpertList)
        self.btn_ShowUserList = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.btn_ShowUserList.setObjectName("btn_ShowUserList")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.btn_ShowUserList)
        self.comboBox = QtWidgets.QComboBox(self.pg_eventList)
        self.comboBox.setGeometry(QtCore.QRect(10, 40, 351, 21))
        self.comboBox.setObjectName("comboBox")
        self.label_62 = QtWidgets.QLabel(self.pg_eventList)
        self.label_62.setGeometry(QtCore.QRect(10, 20, 351, 16))
        self.label_62.setObjectName("label_62")
        self.lst_viewExpertOrUserList = QtWidgets.QListWidget(self.pg_eventList)
        self.lst_viewExpertOrUserList.setGeometry(QtCore.QRect(20, 290, 281, 281))
        self.lst_viewExpertOrUserList.setObjectName("lst_viewExpertOrUserList")
        self.stackedWidget.addWidget(self.pg_eventList)
        self.verticalWidget = QtWidgets.QWidget(self.pg_main)
        self.verticalWidget.setGeometry(QtCore.QRect(0, 0, 200, 600))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_24 = QtWidgets.QLabel(self.verticalWidget)
        self.label_24.setEnabled(True)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_24.setObjectName("label_24")
        self.verticalLayout_2.addWidget(self.label_24)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.blyt_expertPanel = QtWidgets.QVBoxLayout()
        self.blyt_expertPanel.setObjectName("blyt_expertPanel")
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.blyt_expertPanel.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.blyt_expertPanel.addWidget(self.pushButton_6)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.blyt_expertPanel.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.blyt_expertPanel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.MainPages.addWidget(self.pg_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.MainPages.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lucky me"))
        self.pb_Enter.setText(_translate("MainWindow", "Войти"))
        self.label.setText(_translate("MainWindow", "Введите выданный вам при регистрации закрытый ключ"))
        self.pb_registration.setText(_translate("MainWindow", "Зарегестрировать"))
        self.label_2.setText(_translate("MainWindow", "Еще нет аккаунта?"))
        self.label_3.setText(_translate("MainWindow", "Сгенерировать закрытый ключ"))
        self.pb_generatePrivKey.setText(_translate("MainWindow", "Генерация"))
        self.label_4.setText(_translate("MainWindow", "Имя:"))
        self.label_5.setText(_translate("MainWindow", "Фамилия:"))
        self.label_6.setText(_translate("MainWindow", "Отчество:"))
        self.label_7.setText(_translate("MainWindow", "Организация:"))
        self.label_8.setText(_translate("MainWindow", "Должность:"))
        self.label_21.setText(_translate("MainWindow", "Закрытый ключ:"))
        self.label_14.setText(_translate("MainWindow", "Дата рождения:"))
        self.label_22.setText(_translate("MainWindow", "Добро пожаловать в окно регистрации"))
        self.label_23.setText(_translate("MainWindow", "Внимание! После регистрации и принятии транзакции сетью изменить поля будет нельзя, отнеситесь к заполнению этих полей ответственно. Нажмите на кнопку \"Генерация\", чтобы создать закрытый ключ. Самому закрытый ключ создать нельзя в целях безопасности. Закрытый ключ необходимо запомнить или спрятать так, чтобы никто не мог иметь к нему доступа. Закрытый ключ в понимании обычного пользователя является одновременно и логином и паролем, восстановить который нельзя."))
        self.pb_sendRegistReqv.setText(_translate("MainWindow", "Отправить запрос на регистрацию"))
        self.label_25.setText(_translate("MainWindow", "Имя:"))
        self.lbl_imya.setText(_translate("MainWindow", "noname"))
        self.label_26.setText(_translate("MainWindow", "Фамилия:"))
        self.lbl_familiya.setText(_translate("MainWindow", "noname"))
        self.label_27.setText(_translate("MainWindow", "Отчество:"))
        self.lbl_otchestvo.setText(_translate("MainWindow", "noname"))
        self.label_28.setText(_translate("MainWindow", "Организация:"))
        self.lbl_organization.setText(_translate("MainWindow", "default"))
        self.label_29.setText(_translate("MainWindow", "Должность:"))
        self.lbl_post.setText(_translate("MainWindow", "default"))
        self.label_31.setText(_translate("MainWindow", "Дата рождения:"))
        self.lbl_dateOfBirth.setText(_translate("MainWindow", "default"))
        self.label_30.setText(_translate("MainWindow", "Закрытый ключ:"))
        self.lbl_secretKey.setText(_translate("MainWindow", "default"))
        self.label_41.setText(_translate("MainWindow", "Адрес:"))
        self.lbl_adress.setText(_translate("MainWindow", "default"))
        self.label_42.setText(_translate("MainWindow", "Открытый ключ:"))
        self.lbl_openKey.setText(_translate("MainWindow", "default"))
        self.label_32.setText(_translate("MainWindow", "Информация, привязанная к вашему аккаунту"))
        self.pushButton_7.setText(_translate("MainWindow", "Подать заявку на роль эксперта"))
        self.label_43.setText(_translate("MainWindow", "Если ваш аккаунт в системе должен быть в роли эксперта, то вы должны подать заявку и ожидать подтверждения 3мя экспертами. В протином случае ни в коем случае не подавайте заявку на получение роли эксперта, иначе вы можете быть забанены "))
        self.label_44.setText(_translate("MainWindow", "Статус на данный момент:"))
        self.label_45.setText(_translate("MainWindow", "default"))
        self.label_46.setText(_translate("MainWindow", "Id Мероприятия:"))
        self.lbl_idEvent.setText(_translate("MainWindow", "TextLabel"))
        self.label_49.setText(_translate("MainWindow", "Создатель:"))
        self.label_51.setText(_translate("MainWindow", "дата мероприятия:"))
        self.label_55.setText(_translate("MainWindow", "Направление:"))
        self.lbl_EventCompetention.setText(_translate("MainWindow", "TextLabel"))
        self.label_50.setText(_translate("MainWindow", "Оценка:"))
        self.lbl_EventOcenka.setText(_translate("MainWindow", "TextLabel"))
        self.label_57.setText(_translate("MainWindow", "Количество экспертов:"))
        self.lbl_EventNumberOfExpert.setText(_translate("MainWindow", "TextLabel"))
        self.label_61.setText(_translate("MainWindow", "Перечень экспертов:"))
        self.label_56.setText(_translate("MainWindow", "Перечень участников:"))
        self.lbl_EventDate.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_EventCreator.setText(_translate("MainWindow", "TextLabel"))
        self.btn_ShowExpertList.setText(_translate("MainWindow", "Показать"))
        self.btn_ShowUserList.setText(_translate("MainWindow", "Показать"))
        self.label_62.setText(_translate("MainWindow", "Список доступных мероприятий"))
        self.label_24.setText(_translate("MainWindow", "Меню"))
        self.pushButton_2.setText(_translate("MainWindow", "Об аккаунте"))
        self.pushButton_3.setText(_translate("MainWindow", "Мероприятия"))
        self.pushButton_5.setText(_translate("MainWindow", "Создать мероприятие"))
        self.pushButton_6.setText(_translate("MainWindow", "В ожидании"))
        self.pushButton_4.setText(_translate("MainWindow", "Заявка на разжалование"))







if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    # MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.MainPages.setCurrentIndex(0)
    ui.show()
    app.exec_()



